#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🏃 Running Pre-commit Hooks..."

pnpm run lint && pnpm run typecheck

if [ $? -ne 0 ]; then
  echo "❌ Pre-commit validation failed. Please fix the errors before committing."
  exit 1
fi

echo "✅ Pre-commit validation passed."
